import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Sidebar } from "@/components/sidebar";
import { MobileHeader } from "@/components/mobile-header";
import { Toaster } from "@/components/ui/sonner";

const nunito = Nunito({
	subsets: ["latin-ext", "cyrillic-ext"],
});

export const metadata: Metadata = {
	title: "Lingo",
	description: "Generated by create next app",
};

export default function MainLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main>
			<MobileHeader />
			<Sidebar className="hidden lg:flex" />
			<div className="h-full pt-12 lg:pl-64 lg:pt-0">
				<div className="max-w-[1056px] mx-auto h-full pt-6">
					{children}
				</div>
			</div>
		</main>
	);
}
