import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { PracticeModal } from "@/components/modals/practice-modal";

const nunito = Nunito({
	subsets: ["latin-ext", "cyrillic-ext"],
});

export const metadata: Metadata = {
	title: "Lingo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider
			afterSignOutUrl={"/"}
		>
			<html lang="en">
				<body
					className={`${nunito.className} antialiased scheme-only-light`}
				>
					<Toaster richColors />
					<ExitModal />
					<HeartsModal />
					<PracticeModal />

					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
