import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/app/globals.css";
import { Header } from "./_components/header";
import { Footer } from "./_components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const nunito = Nunito({
	subsets: ["latin-ext", "cyrillic-ext"],
});

export const metadata: Metadata = {
	title: "Lingo",
	description: "Generated by create next app",
};

export default function MarketingLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className="flex flex-col min-h-screen">
			<Header />

			<div className="flex flex-col items-center justify-center flex-1">
				{children}
			</div>

			<Footer />
		</main>
	);
}
